FROM python:3.11-slim

ENV PYTHONUNBUFFERED True

# set the working directory
WORKDIR /usr/backend/app

# install dependencies
COPY ./backend/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# copy src code
COPY ./backend ./backend

EXPOSE 4000

# start the server
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "4000", "--proxy-headers"]