FROM python:3.11-slim

ENV PYTHONUNBUFFERED True

# Set the working directory
WORKDIR /usr/app/backend
RUN echo WORKDIR

# Copy requirements file and install dependencies
COPY ./backend ./
RUN pip install --no-cache-dir -r requirements.txt

# Set PYTHONPATH
ENV PYTHONPATH=/usr/app/backend

# # Load environment variables from config.env
# ENV $(grep -v '^#' /usr/app/backend/config/.env | xargs)
# ENV DATABASE_URL=${DATABASE_URL}
# ENV GPT4_API_KEY=${GPT4_API_KEY}

# Expose the port
EXPOSE 8080

# Start the server
CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port ${PORT:-8080} --proxy-headers"]